<?php

/**
 * @file
 * Contains component.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function component_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the component module.
    case 'help.page.component':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function component_theme() {
  $theme = [];
  // get current theme name
  $current_theme = \Drupal::service('theme.manager')->getActiveTheme()->getName();
  // retrieve component types
  $component_types = \Drupal::entityQuery('component_type')->execute();
  foreach($component_types as $component_type) {
    $component = str_replace('_', '-', $component_type);
    // component directory
    $component_dir = drupal_get_path('theme', $current_theme) . '/components/' . $component; 
    if(file_prepare_directory($component_dir)) {
      $theme[$component_type] = [
        'render element' => 'elements',
        'path' => $component_dir,
        'template' => $component,
      ];
    }else {
      $theme[$component_type] = [
        'render element' => 'content',
        'file' => 'component.page.inc',
        'template' => 'component',
      ];
    } 
  }

  $theme['component_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'component.page.inc',
  ];
  return $theme;
}
