<?php

/**
 * @file
 * Contains clutch.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function clutch_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the clutch module.
    case 'help.page.clutch':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Poetic Systems awesome website conversion module.') . '</p>';
      return $output;

    default:
  }
}
